#https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: 'Hello World'
description: 'Greet someone'
inputs:
  secret-input:
    description: 'Input that uses a secret'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set Greeting
      run: echo $INPUT_SECRET_INPUT
      shell: bash
