#https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: 'Hello World'
description: 'Greet someone'
inputs:
  secret-input:
    description: 'Input that uses a secret'
    required: true
runs:
  using: 'docker'
  image: 'test.Dockerfile'
