#https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

name: 'Hello World'
description: 'Greet someone'
inputs:
  github-token:
    description: 'Input that uses a secret'
    required: true
  rules:
    description: 'Input that uses a secret'
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    RULES: ${{inputs.rules}}
    GITHUB_TOKEN: ${{ inputs.github-token }}
