name: PullRequest review labeler
on:
  pull_request_review:
  pull_request:
    types: [ review_requested ]

jobs:
  labeler:
    name: Label PR
    runs-on: ubuntu-22.04
#    container: python:3.10-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip3 install -r requirements.txt
      - name: Run main.py
        run: python3 main.py
        env:
          RULES: '[["TeamRabbit", "rabbits"]]'
          GITHUB_TOKEN: ${{ secrets.LABELER_APP_TOKEN }}
