name: PullRequest review labeler
on:
  pull_request_review:
  pull_request:
    types: [ review_requested ]

jobs:
  labeler:
    name: Label PR
    runs-on: ubuntu-22.04
#    container: python:3.10-alpine
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.LABELER_APP_ID }}
          private-key: ${{ secrets.LABELER_APP_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip3 install -r requirements.txt
      - name: Run main.py
        run: python3 main.py
        env:
          RULES: '[["TeamRabbit", "rabbits"]]'
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
